# Generated by Django 4.2.1 on 2023-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hobbies",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
