# Generated by Django 4.2.1 on 2023-05-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="interests",
            field=models.TextField(blank=True, default="Interests", null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="hobbies",
            field=models.TextField(blank=True, default="Hobbies", null=True),
        ),
    ]
