# Generated by Django 4.2.1 on 2023-05-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dob",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
