# Generated by Django 4.2.1 on 2023-06-09 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reason_for_deactivation",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
