# Generated by Django 4.2.1 on 2023-05-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_customuser_hobbies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="dob",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
