# Generated by Django 4.2.1 on 2023-06-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_profile_reason_for_deactivation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_type",
            field=models.CharField(
                choices=[("Tenant", "Tenant"), ("Landlord", "Landlord")],
                default="Tenant",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="reason_for_deactivation",
            field=models.TextField(default=""),
        ),
    ]
