# Generated by Django 4.2.1 on 2023-05-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_customuser_dob_alter_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
