# Generated by Django 4.2.1 on 2023-05-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_customuser_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
