# Generated by Django 4.2.2 on 2023-08-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profile_profile_type_customuser_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Guest', 'Guest'), ('Host', 'Host')], default='Guest', max_length=255, null=True),
        ),
    ]
