# Generated by Django 4.2.1 on 2023-05-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_customuser_isverified_passwordrecoverylogs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverificationlogs",
            name="user",
        ),
    ]
