# Generated by Django 4.2.1 on 2023-05-13 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_remove_emailverificationlogs_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordrecoverylogs",
            name="user",
        ),
        migrations.AddField(
            model_name="passwordrecoverylogs",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
