# Generated by Django 4.2.2 on 2023-09-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_imagetestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_made_host_request',
            field=models.BooleanField(default=False),
        ),
    ]
